# This is a basic workflow to help you get started with Actions

name: ci-parser

on:
  workflow_dispatch:

jobs:
  ci_parser_try:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - run: ./gradlew clean test --rerun-tasks --stacktrace -Dorg.gradle.java.home=/opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
      
      - run: ls build/test-results
      - run: ls build/test-results/test
        
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: build/test-results/test
